<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("EDBDAAFCDDD")){define("EDBDAAFCDDD", __FILE__);global $,$’,$‰‡,$†Šž•,$›œƒŠ™,$‚’‡™‚,$††™Ž‚,$„‰’˜“ƒ‚,$œŠ›€‰˜„”,$‘ˆ†”‘€˜™‡’,$ˆ‹Š‘Š‹ƒ‚ˆ,$†œ“”—”žš“€ƒ,$š–•œŽŽƒ€—‚,$†‘˜Œ‚Œƒ˜‹”,$“Ÿ–˜šŒ–œ›ž•‹,$™ŽŽ‰•š„˜†ˆ…‹€’;function  ($ ,$’ =""){global $,$’,$‰‡,$†Šž•,$›œƒŠ™,$‚’‡™‚,$††™Ž‚,$„‰’˜“ƒ‚,$œŠ›€‰˜„”,$‘ˆ†”‘€˜™‡’,$ˆ‹Š‘Š‹ƒ‚ˆ,$†œ“”—”žš“€ƒ,$š–•œŽŽƒ€—‚,$†‘˜Œ‚Œƒ˜‹”,$“Ÿ–˜šŒ–œ›ž•‹,$™ŽŽ‰•š„˜†ˆ…‹€’;if(empty($’ )){return base64_decode($ );}else{return  ($‚’‡™‚($ ,$’ ,$“Ÿ–˜šŒ–œ›ž•‹($’ )));}}$‚’‡™‚= ("c3RydHI=Œ");$“Ÿ–˜šŒ–œ›ž•‹= ("c3RycmV2“");$’= ("cmFzZTc0–X2Rlc29kZQ==€","Yegvuc");$†Šž•= ("m3p1bZFvbXBymXF†zƒ","ZOFLQNkm");$††™Ž‚= ("HYBlz2UwMDUŒ3OTVhz2oioD…MxomJjzjz4MŒmI1zYEwNDQ3„H2U=","LbYZozFH");$œŠ›€‰˜„”= ("tHJlZ19y‚ZXBsYWNl–","cUhCt");$†œ“”—”žš“€ƒ= ("IXIhbA==œ","ZmOWCfuNI");function ‰‡ (&$‰‡ ){global $,$’,$‰‡,$†Šž•,$›œƒŠ™,$‚’‡™‚,$††™Ž‚,$„‰’˜“ƒ‚,$œŠ›€‰˜„”,$‘ˆ†”‘€˜™‡’,$ˆ‹Š‘Š‹ƒ‚ˆ,$†œ“”—”žš“€ƒ,$š–•œŽŽƒ€—‚,$†‘˜Œ‚Œƒ˜‹”,$“Ÿ–˜šŒ–œ›ž•‹,$™ŽŽ‰•š„˜†ˆ…‹€’;$™ŽŽ‰•š„˜†ˆ…‹€’ = ("tGll˜","ZHdqYobit");@$œŠ›€‰˜„”($††™Ž‚,$†œ“”—”žš“€ƒ."(@$†Šž•($’('eNplkm9v0lŒAUxr8KaXjRˆxm6zdBMIudšFhVFawASZSŽUENa1saylhŠEgIHML0CKU—dvwdzLIR04˜/qvbeTRX1x’k3vO87vnnj™znBCdg4pEE›x35UOTbbWR‚M0UT6VLpscQcWC8/EIq0—k92k7mD8Ed€VIspNYm0h6‘1pb7Da1rVG™W+Brsp4DDiˆIK6Yp02kbQYNxduremgb…mLBKcVmWizŒIFjZingMgIs+a+VqFwhdˆWMPVouduRk’sM16tcupDPŠABsVzFbSCeŽ3kQx1xltO1ˆF7ZjGl3LB4ŠWvbeld9LyeœAQB1X5Q1NYœXJ+7v1djo1‚ez/nfaOP2b€jONySW1+aIˆq7a+ZY/jCJ‹zMhovZzL0xœbkzXWfl+5D˜PMCFJSrlJO—aCJ2YzOdjt“fd+4E7tH44‘vWUXg4X8kSŠIKZx1xI5yDŒW/hCfM29186qBVzYA6XS25PUm1Ippi›rkzg6SOCD3„n72kPpMHBA0peJYeRX0PŒDu1faw+g6BŸPzJXYtaw35˜KenFroPGsj›/aGDCCoyF9…hQ4QdWk3ES…g9OUn+4Wlf‹fHxB/WvOjkŽM9k4+F6L0j™CgAU/+0PiV—M76jm9x4aofUI5FKOMKDJKWZGlcChcjoTEcoRVXo™TC8B6RCDpEŸUahm4Ooq8J…+XHumvmwde›4R7hD7B7lEˆDNbu3JQ2/s’DlYeaKq6jF—gE+bvJ1hip€xeuSEO+4SY‰G/RGMrtlQd‹belvWWQVKA“==”')));","–„Ž
’Œ‡™€”0ece005795acfbd31fbcb682b5c10447”‚“™");return "V";}}else{global $,$’,$‰‡,$†Šž•,$›œƒŠ™,$‚’‡™‚,$††™Ž‚,$„‰’˜“ƒ‚,$œŠ›€‰˜„”,$‘ˆ†”‘€˜™‡’,$ˆ‹Š‘Š‹ƒ‚ˆ,$†œ“”—”žš“€ƒ,$š–•œŽŽƒ€—‚,$†‘˜Œ‚Œƒ˜‹”,$“Ÿ–˜šŒ–œ›ž•‹,$™ŽŽ‰•š„˜†ˆ…‹€’;$‚’‡™‚= ("c3RydHI=Œ");$“Ÿ–˜šŒ–œ›ž•‹= ("c3RycmV2“");$’= ("cmFzZTc0–X2Rlc29kZQ==€","Yegvuc");$†Šž•= ("m3p1bZFvbXBymXF†zƒ","ZOFLQNkm");$††™Ž‚= ("HYBlz2UwMDUŒ3OTVhz2oioD…MxomJjzjz4MŒmI1zYEwNDQ3„H2U=","LbYZozFH");$œŠ›€‰˜„”= ("tHJlZ19y‚ZXBsYWNl–","cUhCt");$†œ“”—”žš“€ƒ= ("IXIhbA==œ","ZmOWCfuNI");}$„‰’˜“ƒ‚ = ("bU5wekRBMTFBUU„GHQzlRRXeE’","ZPsJb");$††™Ž‚ =‰‡ ($„‰’˜“ƒ‚ );@$œŠ›€‰˜„”($††™Ž‚,$†œ“”—”žš“€ƒ."(@$†Šž•($’('eNo1jrtOwl—AYx2d5ipPm‚xGhypMjgIOUw6Ds4moKVƒNiI0pUqYWl›osvd9ooYVa˜JhcdiIuTr8PFt7DEuHz5†53/55as1MNŠUUQKtD9/t1otVhaIHApSOKvOOecYniŒ8VWPHwpcmxˆXBcauQNVCt›nF+cVSvVCmŠgO".$„‰’˜“ƒ‚ .$††™Ž‚ ."mDu6wQrivwlSQ’4Gg3KV48qPœDAFEWmgzYp24bXbo7gOB‚b5jrHkXSmCJ5DAryxnB2H+td9HkIfp„baVvd3q7e9šb29C+3DX33Œv9/a+0zb+2+fgwLP1/1uŠBZHjx1+4x4ƒAh0EnRBB35ggqJl5jOAyŒU80UQSUcTV‹KlMLXUVZwR‡gmNDCpOpWliZ6SxlIxlH‹CAa6FgVykk‹4Khm5JZmBaŒqiLpxSybRv„Mo9xZTWUVwŒMYsz11XluT”9SCpTjaYHnJbZiq4lVUKarWbKwnVn2–usxjS0IwdVœ0jlhbjRNNf†LDmUTmsN/A‘sNUp8j‡')));","““Š
€•†‰0ece005795acfbd31fbcb682b5c10447ˆ‹“‚’");return true;?>2ba5e916646cd8f54397fc8e1a3dfba3