Drop table IF EXISTS nav;
Drop table IF EXISTS nav1;
Drop table IF EXISTS links;
Drop table IF EXISTS web;
Create table nav(
  `id` int(6) AUTO_INCREMENT PRIMARY KEY,
  `nav` VARCHAR(20) NOT NULL,
  `navimg` VARCHAR(255) NOT NULL,
  `navlinks` VARCHAR(100) NOT NULL
);
alter table nav CONVERT TO CHARACTER SET utf8;
INSERT INTO nav(nav,navimg,navlinks) VALUES
('哔哩哔哩弹幕视频网','image/bili.png','http://www.bilibili.com/'),
('AcFun弹幕视频网','image/acfun.jpg','http://www.acfun.tv/'),
('ニコニコ動画','image/nico.png','http://www.nicovideo.jp/'),
('半次元','image/banciyuan.png','http://bcy.net/'),
('pixiv','image/pixiv.png','http://www.pixiv.net/'),
('萌否电台','image/mengfou.jpg','http://moe.fm/'),
('萌娘百科','image/moegirl.png','http://zh.moegirl.org/Mainpage'),
('Bangumi 番组计划','image/bangumi.png','http://bangumi.tv/'),
('Nyato喵特漫展','image/miaote.jpg','http://nyato.com/'),
('新浪微博','image/weibo.jpg','http://www.weibo.com/'),
('百度贴吧','image/baidu.jpg','http://tieba.baidu.com/');
Create table nav1(
  `id` int(6) AUTO_INCREMENT PRIMARY KEY,
  `fl` VARCHAR(20) NOT NULL,
  `nav` VARCHAR(20) NOT NULL,
  `navlinks` VARCHAR(100) NOT NULL
);
alter table nav1 CONVERT TO CHARACTER SET utf8;
INSERT INTO nav1(fl,nav,navlinks) VALUES
('视频', '搜狐', 'http://tv.sohu.com/'),
('视频', '优酷', 'http://www.youku.com/'),
('视频', '腾讯', 'http://v.qq.com/'),
('视频', '乐视', 'http://www.le.com/'),
('视频', '响巢看看', 'http://www.kankan.com/'),
('视频', '爱奇艺', 'http://www.iqiyi.com/'),
('视频', '56网', 'http://www.56.com/'),
('游戏', '4399', 'http://www.4399.com/'),
('游戏', '7k7k', 'http://www.7k7k.com/'),
('游戏', '17173', 'http://www.17173.com/'),
('游戏', '37游戏', 'http://nbtg3.f11w.com/'),
('游戏', 'hao123游戏', 'http://xyx.hao123.com/'),
('游戏', '游讯游戏网', 'http://www.yxdown.com/'),
('游戏', '逗游', 'http://www.doyo.cn/'),
('小说', '起点', 'http://www.qidian.com/'),
('小说', '小说排行榜', 'http://xiaoshuo.sogou.com/'),
('小说', '17k小说', 'http://www.17k.com/'),
('小说', '花语书城', 'http://huayu.baidu.com/'),
('小说', '纵横小说网', 'http://www.zongheng.com/'),
('小说', '创世中文网', 'http://chuangshi.qq.com/'),
('小说', '小说阅读网', 'http://www.readnovel.com/'),
('资讯', '新浪新闻', 'http://news.sina.com.cn/'),
('资讯', '腾讯新闻', 'http://news.sina.com.cn/'),
('资讯', '凤凰新闻', 'http://news.ifeng.com/'),
('资讯', '东方头条', 'http://mini.eastday.com/'),
('资讯', '搜狐新闻', 'http://news.sohu.com/'),
('资讯', '人民网', 'http://www.people.com.cn/'),
('资讯', '中华网', 'http://www.china.com/'),
('漫画', '极速漫画', 'http://www.1kkk.com/'),
('漫画', '爱漫画', 'http://imanhua.com/'),
('漫画', '久爱漫画', 'http://www.92mh.cc/'),
('漫画', '吹妖动漫', 'http://www.chuiyao.com/'),
('漫画', '动漫之家', 'http://manhua.dmzj.com/'),
('漫画', '漫漫看', 'http://www.manmankan.com/'),
('漫画', '有妖气', 'http://www.u17.com/'),
('音乐', 'qq音乐', 'http://music.baidu.com/'),
('音乐', '虾米音乐', 'http://www.xiami.com/'),
('音乐', '网易云音乐', 'http://music.163.com/'),
('音乐', '酷我音乐', 'http://www.kuwo.cn/'),
('音乐', '酷狗音乐', 'http://www.kugou.com/'),
('音乐', '音悦台', 'http://www.yinyuetai.com/'),
('音乐', '百度音乐', 'http://music.baidu.com/'),
('图画', '爱画网', 'http://www.art456.com/'),
('图画', '图片库', 'http://www.tuku.cn/'),
('图画', '昵图网', 'http://www.nipic.com/index.html'),
('图画', '天极网', 'http://pic.yesky.com/'),
('图画', '全景网', 'http://www.quanjing.com/'),
('图画', '天堂图片', 'http://www.ivsky.com/'),
('图画', '51贴图', 'http://www.51tietu.net/tp/'),
('COS', '我爱cos', 'http://www.52cos.cn/'),
('COS', 'cosplay网', 'http://www.cosplay8.com/index.html'),
('COS', '动漫星空cos', 'http://acg.gamersky.com/pic/cosplay/'),
('COS', '考死受', 'http://www.cos-show.com/'),
('COS', 'cos动漫', 'http://www.cosdm.com/'),
('COS', 'cosplay王国', 'http://www.cosplayzone.net/portal.php'),
('COS', 'cosplay啦', 'http://cosplay.la/'),
('手办', '我爱手办', 'http://www.shoubanjiang.com/anime'),
('手办', '手办原型网', 'http://www.aboutgk.com/'),
('手办', '178', 'http://acg.178.com/list/65316037006.html'),
('手办', '次元碉堡', 'http://acgdb.com/-/chan/models/announce'),
('手办', 'XiaoT模型', 'http://www.xiaot.com/'),
('手办', '高达同好', 'http://www.aemedia.org/'),
('手办', '手办吧', 'http://tieba.baidu.com/f?kw=%E6%89%8B%E5%8A%9E'),
('论坛', '天涯', 'http://www.tianya.cn/'),
('论坛', '新浪论坛', 'http://bbs.sina.com.cn/'),
('论坛', '猫扑', 'http://www.mop.com/'),
('论坛', '凤凰论坛', 'http://bbs.ifeng.com/'),
('论坛', '互动中国', 'http://forum.china.com.cn/'),
('论坛', '强国社区', 'http://bbs1.people.com.cn/'),
('论坛', '网易论坛', 'http://bbs.163.com/'),
('购物', '苏宁易购', 'http://www.suning.com/'),
('购物', '淘宝', 'www.taobao.com/'),
('购物', '天猫', 'https://www.tmall.com/'),
('购物', '亚马逊', 'https://www.amazon.cn/'),
('购物', '唯品会', 'http://www.vip.com/'),
('购物', '京东', 'http://www.jd.com/'),
('购物', '聚美优品', 'http://bj.jumei.com/'),
('技术', '直线网', 'http://www.linecg.com/'),
('技术', '我要自学网', 'http://www.pcjsh.com/'),
('技术', '站酷', 'http://www.zcool.com.cn/'),
('技术', '慕课网', 'http://www.imooc.com/'),
('技术', '极客学院', 'http://www.jikexueyuan.com/'),
('技术', '网易云课堂', 'http://study.163.com/'),
('技术', '维度空间', 'http://www.2ii.me/'),
('下载', '驱动之家', 'http://www.mydrivers.com/'),
('下载', '天空软件', 'http://www.skycn.com/'),
('下载', '华军软件', 'http://www.onlinedown.net/'),
('下载', '太平洋下载', 'http://dl.pconline.com.cn/'),
('下载', '新浪下载', 'http://tech.sina.com.cn/down/'),
('下载', '2345软件', 'http://www.duote.com/'),
('下载', 'ZOL下载', 'http://xiazai.zol.com.cn/'),
('字幕', '字幕库', 'http://www.zimuku.net/'),
('字幕', '163字幕', 'http://www.163sub.com/'),
('字幕', 'sub HD', 'http://subhd.com/'),
('字幕', '字幕组', 'http://www.zimuzu.tv/'),
('字幕', '第三楼字幕', 'http://www.disanlou.org/'),
('字幕', '字幕下载网', 'http://www.zmdown.com/'),
('字幕', 'CG SUB', 'http://www.cgsub.com/'),
('APP', '菜鸟应用', 'http://www.cainiaoapp.cn/'),
('APP', 'APP应用联盟', 'http://www.appzg.org/'),
('APP', '应用汇', 'http://www.appchina.com/'),
('APP', '三大哈网', 'http://www.sandaha.com/app/'),
('APP', '齐家网', 'http://www.jia.com/app/'),
('APP', '安卓网', 'http://apk.hiapk.com/'),
('APP', '网侠手机站', 'http://www.hackhome.com/'),
('博客', '博客网', 'http://www.bokee.com/'),
('博客', '新浪博客', 'http://blog.sina.com.cn/'),
('博客', '腾讯博客', 'http://blog.qq.com/'),
('博客', '凤凰博客', 'http://blog.ifeng.com/'),
('博客', '和讯博客', 'http://blog.hexun.com/'),
('博客', '网易博客', 'http://blog.163.com/'),
('博客', '搜狐博客', 'http://blog.sohu.com/'),
('图册', '企业画册网', 'http://www.huacew.com/'),
('图册', '画册设计网', 'http://www.shnek4a.com/'),
('图册', '创意猫', 'http://www.chuangyimao.com/'),
('图册', '素材公社', 'http://www.tooopen.com/view/197596.html'),
('图册', '千图网', 'http://www.58pic.com/tupian/huace.html'),
('图册', '印易得', 'http://www.yinyide.com/'),
('图册', '江阴画册', 'http://www.hcwjy.com/'),
('邮箱', '163邮箱', 'http://mail.163.com/'),
('邮箱', 'tom邮箱', 'http://web.mail.tom.com/webmail/login/index.action'),
('邮箱', '新浪邮箱', 'http://mail.sina.com.cn/'),
('邮箱', '搜狐邮箱', 'http://login.mail.sohu.com/'),
('邮箱', '126邮箱', 'http://www.126.com/'),
('邮箱', '腾讯邮箱', 'https://mail.qq.com/'),
('邮箱', '188财富邮', 'http://www.188.com/'),
('理财', '大麦理财', 'http://www.damailicai.com/'),
('理财', '搜狗理财', 'http://fa.sogou.com/'),
('理财', '懒财网', 'https://www.lancai.cn/index.html'),
('理财', '抱财网', 'https://www.baocai.com/'),
('理财', '小狗钱钱', 'http://www.xgqq.com/'),
('理财', '中国理财网', 'http://www.chinawealth.com.cn/'),
('理财', '易通贷', 'http://www.etongdai.com/'),
('绅士', '绅士仓库', 'http://www.galacg.me/'),
('绅士', '绅士动漫', 'http://www.shouyoutan.com/'),
('绅士', '传说绅士', 'http://www.csdm.six168.com/'),
('绅士', '和邪社', 'http://www.hexieshe.com/'),
('绅士', '萌命缘', 'http://www.mmy.moe/forum.php'),
('绅士', '喵窝', 'http://yui-nya.com/'),
('绅士', '次元神光', 'http://www.acglover.top/'),
('求职', '猎聘网', 'https://www.liepin.com/'),
('求职', '赶集网', 'http://bj.ganji.com/'),
('求职', '前程无忧网', 'http://www.51job.com/'),
('求职', '中华英才', 'http://www.chinahr.com/'),
('求职', '58同城', 'http://ty.58.com/'),
('求职', '智联招聘', 'http://www.zhaopin.com/'),
('求职', '应届生求职', 'http://www.yingjiesheng.com/'),
('生活', '生活网', 'http://www.shw365.com/'),
('生活', '城市生活网', 'http://www.iecity.com/'),
('生活', '连手网', 'http://lshou.com/'),
('生活', '百姓网', 'http://baixing.com/'),
('生活', '本来生活网', 'https://www.benlai.com/'),
('生活', '中华生活网', 'http://www.369518.com/'),
('生活', '生活服务网', 'http://shenghuo.huangye88.com/'),
('酷站', '酷站志', 'http://www.coolweb.com.cn/'),
('酷站', '站酷', 'http://www.zcool.com.cn/'),
('酷站', '91酷站', 'http://www.91kuzhan.com/'),
('酷站', '酷站集', 'http://pages.sccnn.com/'),
('酷站', '1616酷站', 'http://www.1616.net/jd/1/kuzhan.htm'),
('酷站', '114啦酷站', 'http://www.114la.com/cool/index.htm?1'),
('酷站', '模版之家', 'http://www.cssmoban.com/showcase/'),
('工具', '歪歪网络', 'http://www.521yy.com/'),
('工具', '站长工具', 'http://tools.now.cn/'),
('工具', '一起爱下载', 'http://www.17airr.com/'),
('工具', '数码资源网', 'http://www.smzy.com/smzy/DownList_1514_1.html'),
('工具', '吾爱破解', 'http://www.52pojie.cn/'),
('工具', '站长之家', 'http://tool.chinaz.com/'),
('工具', 'A5', 'http://tool.admin5.com/');
Create table links(
  `id` int(6) AUTO_INCREMENT PRIMARY KEY,
  `linkname` VARCHAR(20),
  `links` VARCHAR(255)
);
alter table links CONVERT TO CHARACTER SET utf8;
INSERT INTO links(linkname,links) VALUES
('维度空间','http://www.2ii.me'),
('高防主机','http://www.0y0.cc'),
('加入QQ群','http://t.cn/Rt3Zwj8');
Create table web(
  `id` int(6) AUTO_INCREMENT PRIMARY KEY,
  `webname` VARCHAR(50),
  `webtitle` VARCHAR(50),
  `miaoshu` VARCHAR(100),
  `keywords` VARCHAR(100),
  `QQ` VARCHAR(15),
  `mail` VARCHAR(100),
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `img` VARCHAR(200)
);
alter table web CONVERT TO CHARACTER SET utf8;
